// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB15hiLigPCnXVb2hoEDWBevbHydQkz2E0',
    appId: '1:1076862297909:web:f0667990818ad41d1e8e7c',
    messagingSenderId: '1076862297909',
    projectId: 'habittracker-fd23c',
    authDomain: 'habittracker-fd23c.firebaseapp.com',
    storageBucket: 'habittracker-fd23c.firebasestorage.app',
    measurementId: 'G-FQKWHN2CPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZuAFDpmW2otmZX8v1Y8Vj-lEYKymn8Q',
    appId: '1:1076862297909:android:3852cb6d3240f5cf1e8e7c',
    messagingSenderId: '1076862297909',
    projectId: 'habittracker-fd23c',
    storageBucket: 'habittracker-fd23c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN4DjouiPKJKGNaHcRjtT-zKNJUHl8XEY',
    appId: '1:1076862297909:ios:e0df8b9a167ceda21e8e7c',
    messagingSenderId: '1076862297909',
    projectId: 'habittracker-fd23c',
    storageBucket: 'habittracker-fd23c.firebasestorage.app',
    iosBundleId: 'com.example.mainproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN4DjouiPKJKGNaHcRjtT-zKNJUHl8XEY',
    appId: '1:1076862297909:ios:e0df8b9a167ceda21e8e7c',
    messagingSenderId: '1076862297909',
    projectId: 'habittracker-fd23c',
    storageBucket: 'habittracker-fd23c.firebasestorage.app',
    iosBundleId: 'com.example.mainproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB15hiLigPCnXVb2hoEDWBevbHydQkz2E0',
    appId: '1:1076862297909:web:b63080547d2dae4a1e8e7c',
    messagingSenderId: '1076862297909',
    projectId: 'habittracker-fd23c',
    authDomain: 'habittracker-fd23c.firebaseapp.com',
    storageBucket: 'habittracker-fd23c.firebasestorage.app',
    measurementId: 'G-7LC7G47WRX',
  );

}